In [ ]:
import numpy as np

In [ ]:
my_arr = np.arange(100) # 배열
print(my_arr)

my_list = list(range(100)) # 리스트
print(my_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
data = np.random.randn(2, 3) # 2x3 배열
print(data)

print(data * 10)

print(data.shape) # tuple 형태

[[-0.10098452  0.96375849 -0.1199769 ]
 [-0.17186041 -0.10490635  0.5807002 ]]
[[-1.00984523  9.63758487 -1.19976904]
 [-1.71860411 -1.04906352  5.80700205]]
(2, 3)


In [ ]:
# list -> array
data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print(arr1)

[1 2 3 4 5]


In [ ]:
# 2차원 배열로 변경
data2 = [1,2,3,4,5], [11,12,13,14,15]
arr2 = np.array(data2)
print(arr2)
print(arr2.shape, ',', arr2.ndim) # ndim: 차원의 수

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
(2, 5) , 2


In [ ]:
# 3차원 배열
arr3d = np.array([[[1,2,3], [4,5,6]], [[11,12,13], [14,15,16]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [ ]:
matrix = np.arange(1,7) # vector 형태로 만들어짐(출력시 리스트형태이지만 value들을 ,로 나누지 않고 있음)
print(matrix)

# reshape(차수를 변경)
matrix = np.arange(1,7).reshape(2,3)
print(matrix)
print(matrix.sum()) # value들의 합
print(matrix.sum(axis=0)) # row에 대해서
print(matrix.sum(axis=1)) # colum에 대해서

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


In [ ]:
# 3차원 데이터 = tensor
# list = [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]
tensor = np.arange(1, 19).reshape(3,2,3)
print(tensor)
print('SUM = ', tensor.sum(axis=None))
print('SUM = ', tensor.sum(axis=0))
print('SUM = ', tensor.sum(axis=1))
print('SUM = ', tensor.sum(axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
SUM =  171
SUM =  [[21 24 27]
 [30 33 36]]
SUM =  [[ 5  7  9]
 [17 19 21]
 [29 31 33]]
SUM =  [[ 6 15]
 [24 33]
 [42 51]]


In [ ]:
# mean
matrix = np.arange(1, 7).reshape(2,3)
print(matrix.mean())
print(matrix.mean(axis=0))
print(matrix.mean(axis=1))

3.5
[2.5 3.5 4.5]
[2. 5.]


In [ ]:
# 수직(vstack) 세로 axis = 0

matrix1 = np.array([1,2,3]) #1x3
matrix2 = np.array([4,5,6]) #1x3
print(matrix1)
print(matrix2)
print(np.vstack((matrix1, matrix2))) # 2 x 3

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 수평(hstack) 가로 axis = 1
matrix1 = np.array([1,2,3]).reshape(3,1) #1x3 -> 3x1
matrix2 = np.array([4,5,6]).reshape(3,1) #1x3 -> 3x1
print(matrix1)
print(matrix2)
print(np.hstack((matrix1, matrix2))) # 3 x 2

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
matrix1 = np.array([1,2,3]) #1x3
matrix2 = np.array([4,5,6]) #1x3
print(np.concatenate((matrix1, matrix2), axis=0))

matrix3 = np.array([1,2,3]).reshape(3,1) #1x3 -> 3x1
matrix4 = np.array([4,5,6]).reshape(3,1) #1x3 -> 3x1

print(np.concatenate((matrix3, matrix4), axis=1))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


Quiz) 1~ 30의 실수로 이루어진 5x6 형태의 데이터 행렬을 만든 후 조건에 맞는 코드 작성

- 전체의 최대값
- 행의 합
- 열의 평균

In [ ]:
# Quiz 1
import numpy as np

data = np.arange(1, 31, dtype=np.float).reshape(5, 6)
print(data)
print(data.max())
print(data.sum(axis=1))
print(data.mean(axis=0))

# 정답
print(np.max(matrix))
print(np.sum(matrix, axis=1))
print(np.mean(matrix, axis=0))

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]]
30.0
[ 21.  57.  93. 129. 165.]
[13. 14. 15. 16. 17. 18.]


In [ ]:
# Quiz 2
import numpy as np

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[10], [20]])

print(np.hstack((a, b)))

[[ 1  2  3 10]
 [ 4  5  6 20]]
[[10]
 [20]]


In [ ]:
# Quiz 3
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20, 30])

print(np.vstack((a, b)))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [ ]:
# Quiz 4
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[10, 20]])

print(np.hstack((a, b.T))) # .T : transpose 행과 열을 바꾸어준다.

[[ 1  2  3 10]
 [ 4  5  6 20]]


In [ ]:
# Quiz 5
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20]).reshape(2,1)

print(np.hstack((a, b)))

[[ 1  2  3 10]
 [ 4  5  6 20]]


In [77]:
a = np.arange(1, 7).reshape(2,3)
b = np.arange(11, 17).reshape(3,2)
print(a.dot(b)) # 행렬 곱

print(a)
print(a.T)
print(a.dot(a.T))

[[ 82  88]
 [199 214]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [79]:
# broadcasting
# 하나의 데이터가 모든 데이터에 적용
scalar = 10
tensor = np.array(
    [
     [[1,2,3], [4,5,6]],
     [[7,8,9], [10,11,12]],
     [[13,14,15], [16,17,18]] 
     ]
)
print(scalar * tensor)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[130 140 150]
  [160 170 180]]]


In [80]:
import numpy as np 

vector1 = np.array([[1], [2], [3]])
vector2 = np.array([11, 12, 13])
print(vector1 * vector2)

[[11 12 13]
 [22 24 26]
 [33 36 39]]


In [86]:
# Quiz 1
import numpy as np
matrix1 = np.arange(1, 13).reshape(3, 4)
matrix2 = np.arange(12, 0, -1).reshape(3, 4)
# 코드 작성
print(matrix1.dot(matrix2.T))

[[100  60  20]
 [268 164  60]
 [436 268 100]]


In [87]:
# Quiz 2
import numpy as np
vector = np.array([10, 20, 30])

# 코드 작성
scalar = 2

# 출력
print(vector * scalar)

[20 40 60]


In [ ]:
# Quiz 3
import numpy as np
matrix = np.([[10], [20], [30]])


In [93]:
# Quiz 4
import numpy as np
vector = np.array([10, 20, 30])
# 코드 작성
matrix = np.array([[1], [2], [3]])
# 출력
print(vector + matrix)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# Quiz 5

In [90]:
# Quiz 6
import numpy as np

matrix = np.array([
                   [10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]
])

# 코드 작성
vector = np.array([[1],[2],[3]])
# 출력
print(matrix + vector)

[[11 21 31]
 [42 52 62]
 [73 83 93]]
