In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
data = np.loadtxt('ex1_지역별전기요금.csv', delimiter=',', dtype=np.int, encoding='cp949')

In [8]:
# Q1
print(data[:5,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [9]:
# Q2
print(data.shape)

(17, 4)


In [22]:
# Q3 유니크한 값들
print(np.unique(data[:, 0]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [26]:
# Q4
print(np.sum(data[:, 1]))

14882047


In [27]:
# Q5
print(np.mean(data[:, 2]))

335.1764705882353


In [33]:
# Q6

data[data[:, 2] > 400, 0:2]


array([[      2, 2827233],
       [     10,   49394]])

In [35]:
data[:,2] > 400

array([False,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False])