In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [62]:
import numpy as np
data = np.loadtxt('ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=np.float, encoding='cp949')

In [61]:
# Q1
print(data)

[[ 2.014e+03  1.000e+00  2.180e+02  4.800e+00 -9.000e+00 -4.000e+00]
 [ 2.014e+03  2.000e+00  8.720e+02  1.900e+01 -4.500e+01 -4.900e+00]
 [ 2.014e+03  3.000e+00  4.010e+02  8.700e+00 -4.500e+01 -1.010e+01]
 [ 2.014e+03  4.000e+00  4.640e+02  1.010e+01 -4.100e+01 -8.100e+00]
 [ 2.014e+03  5.000e+00  9.900e+01  2.200e+00 -5.000e+00 -4.800e+00]
 [ 2.014e+03  6.000e+00  1.820e+02  4.000e+00  1.900e+01  1.170e+01]
 [ 2.014e+03  7.000e+00  9.900e+01  2.200e+00  8.000e+00  8.800e+00]
 [ 2.014e+03  8.000e+00  1.630e+02  3.600e+00 -4.700e+01 -2.240e+01]
 [ 2.014e+03  9.000e+00  3.860e+02  8.400e+00  1.400e+01  3.800e+00]
 [ 2.014e+03  1.000e+01  2.000e+01  4.000e-01  0.000e+00  0.000e+00]
 [ 2.014e+03  1.100e+01  1.030e+02  2.200e+00 -1.600e+01 -1.340e+01]
 [ 2.014e+03  1.200e+01  1.440e+02  3.100e+00 -6.000e+00 -4.000e+00]
 [ 2.014e+03  1.300e+01  4.000e+02  8.700e+00 -3.500e+01 -8.000e+00]
 [ 2.014e+03  1.400e+01  3.170e+02  6.900e+00 -3.500e+01 -9.900e+00]
 [ 2.014e+03  1.500e+01  8.600e+01

In [55]:
# Q2
print(data.shape)

(17, 6)


In [56]:
# Q3
print(np.unique(data))

[-4.700e+01 -4.500e+01 -4.100e+01 -3.500e+01 -3.100e+01 -2.240e+01
 -1.600e+01 -1.400e+01 -1.340e+01 -1.140e+01 -1.010e+01 -9.900e+00
 -9.000e+00 -8.100e+00 -8.000e+00 -6.000e+00 -5.000e+00 -4.900e+00
 -4.800e+00 -4.000e+00 -1.300e+00  0.000e+00  4.000e-01  1.000e+00
  1.900e+00  2.000e+00  2.200e+00  3.000e+00  3.100e+00  3.600e+00
  3.800e+00  4.000e+00  4.800e+00  5.000e+00  5.300e+00  6.000e+00
  6.900e+00  7.000e+00  8.000e+00  8.400e+00  8.700e+00  8.800e+00
  9.000e+00  1.000e+01  1.010e+01  1.100e+01  1.170e+01  1.200e+01
  1.300e+01  1.400e+01  1.500e+01  1.600e+01  1.700e+01  1.900e+01
  2.000e+01  8.600e+01  9.900e+01  1.030e+02  1.440e+02  1.630e+02
  1.820e+02  2.180e+02  2.420e+02  3.170e+02  3.860e+02  3.870e+02
  4.000e+02  4.010e+02  4.640e+02  8.720e+02  2.014e+03]


In [57]:
# Q4
print(data[7, :])

[2014.     8.   163.     3.6  -47.   -22.4]


In [49]:
# Q5
print(np.sum(data[:, 2]))

4583.0


In [51]:
# Q6
print(np.min(data[:, 5]))

-22.4


In [53]:
# Q7
print(data[data[:, 2] > 400, 4:])


[[-45.   -4.9]
 [-45.  -10.1]
 [-41.   -8.1]]
